// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCwNM-4ye69MZqozTRFW1rJX7IqHJLTs',
    appId: '1:658224185587:web:995e3bfaaae518197df786',
    messagingSenderId: '658224185587',
    projectId: 'mynote-alamino',
    authDomain: 'mynote-alamino.firebaseapp.com',
    storageBucket: 'mynote-alamino.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGVUgmxPSZt3VS6FkiXK-7Ijq1hPlFKKQ',
    appId: '1:658224185587:android:3622044aa29077887df786',
    messagingSenderId: '658224185587',
    projectId: 'mynote-alamino',
    storageBucket: 'mynote-alamino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVyxTFHHWWE2UKUwbv-fysg5Mu_8b8DmQ',
    appId: '1:658224185587:ios:186ff9442b999f107df786',
    messagingSenderId: '658224185587',
    projectId: 'mynote-alamino',
    storageBucket: 'mynote-alamino.appspot.com',
    iosBundleId: 'com.note.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVyxTFHHWWE2UKUwbv-fysg5Mu_8b8DmQ',
    appId: '1:658224185587:ios:186ff9442b999f107df786',
    messagingSenderId: '658224185587',
    projectId: 'mynote-alamino',
    storageBucket: 'mynote-alamino.appspot.com',
    iosBundleId: 'com.note.mynote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqCwNM-4ye69MZqozTRFW1rJX7IqHJLTs',
    appId: '1:658224185587:web:153c9174a176fece7df786',
    messagingSenderId: '658224185587',
    projectId: 'mynote-alamino',
    authDomain: 'mynote-alamino.firebaseapp.com',
    storageBucket: 'mynote-alamino.appspot.com',
  );
}
